apiVersion: v1
kind: Service
metadata:
  labels:
    service: persons-service
  name: persons-service
spec:
  ports:
  - name: "5000"
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30001
  selector:
    service: persons-service
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: persons-service
  name: persons-service
spec:
  replicas: 1
  selector:
    matchLabels:
      service: persons-service
  template:
    metadata:
      labels:
        service: persons-service
    spec:
      containers:
      - image: ihnatenkolv/persons-service:latest
        name: persons-service
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
